#!/usr/bin/env python
import subprocess

# WARNING Don't run this on a production machine

from gps import Gps
g = Gps()

time = g.time()
command = 'date --set {}:{}:{}'.format(*time)
subprocess.call(command, shell=True)
